#ifndef _HAILO_PCIE_VERSION_H_
#define _HAILO_PCIE_VERSION_H_

#include "..\..\common\hailo_pcie_version.h"

#define STRINGIFY_EXPANDED( x ) #x
#define STRINGIFY_NUMBER( x ) STRINGIFY_EXPANDED(x)
#define HAILO_DRV_VER STRINGIFY_NUMBER(HAILO_DRV_VER_MAJOR) "." STRINGIFY_NUMBER(HAILO_DRV_VER_MINOR) "."  STRINGIFY_NUMBER(HAILO_DRV_VER_REVISION)

#endif /* _HAILO_PCIE_VERSION_H_ */
